### ISSUE TITLE
Support capturing back button

### ISSUE THREAD

**Issue by mehmetf** [domokit/sky_sdk#21]
I see no way of capturing the back button press in the app. Currently this closes the Sky Engine.

It would be great if this can be combined with the request to have framework level support for page transitions (with animations). Back button can then be handled within framework and transition to the previous page.

**Comment by eseidelGoogle** [comment]
Agreed.  @mpcomplete looked into this briefly, but we don't yet have a way to override this behavior.

**Comment by mehmetf** [comment]
This _should_ be relatively easy since all you really need is to capture this in java layer and call some dart hook to decide whether the app should handle it or not. See http://developer.android.com/reference/android/app/Activity.html#onBackPressed() The only thing is I am not sure if it can be done in an async way and whether that's a requirement for you.

**Comment by Hixie** [comment]
The reason it's hard is that we need to figure out what it should mean.

**Comment by Hixie** [comment]
Anyway, this is covered by https://github.com/domokit/mojo/issues/155 .

**Comment by b-cancel** [comment]
I'm posting this here in case anyone out there finds this and wishes they would find a simple example
https://gist.github.com/b-cancel/0ca372017a25f0c120b14dfca3591aa5
