### ISSUE TITLE
Minor: InkWell executes ripples on touch down

### ISSUE THREAD

**Issue by mehmetf** [domokit/sky_sdk#24]
I believe the material specification says ripples should expand after a completed tap (touch down and up). Right now they start and expand on touch down which means when I scroll the stocks app, I see ripples where I grab the list. See the polymer material design page on mobile to see what the expected behavior is: https://www.polymer-project.org/0.5/docs/elements/material.html#touch-ripple-effect

**Comment by Hixie** [comment]
Yeah, we match neither the spec nor Android's interpretation of the spec, currently.

**Comment by Hixie** [comment]
...though that page, even on mobile, acts like Stock does. I'm not sure I understand the precise issue you're raising here.

Anyway, this is covered by: https://github.com/domokit/mojo/issues/172

**Comment by mehmetf** [comment]
@Hixie Not really. If you tap and hold the button on the material page, the ripple does not propagate. You are right that this is covered by domokit/mojo#172.

Main reason for raising this: When I scroll on the stocks app, the scrolling gesture initiates the ripple effect on whichever list item my finger happens to touch. This is not pleasing to eye. If I interpret material design page correctly, the ripple should only be executed on elements I am interacting with. If I am scrolling the list, I am not interacting with listitem, I am interacting with the list.

**Comment by Hixie** [comment]
When I push down on any of the squares on that page on my phone, I get a ripple straight away.
On Android L system widgets, the ripples are still there, but very slow.

On the tip-of-tree stock version, the ripples are quenched when you scroll, which makes it much less of a problem. But yeah, we should do even better, as per that aforementioned issue.
