### ISSUE TITLE
HTML Support?

### ISSUE THREAD

**Issue by spierce7** [domokit/sky_sdk#25]
So let's say there was a case where a server sends dynamic content for your mobile app to display to the user, and it does so by feeding HTML to the app. Does Sky have a way of taking that HTML and displaying it to the user? Obviously in Android / iOS the dev would just use a WebView. Is / will there be something to handle this in Sky?

**Comment by abarth** [comment]
Sky doesn't have a way to display HTML.  We might add something like that in the future, but probably not for a while.

**Comment by Hixie** [comment]
WebView is https://github.com/flutter/flutter/issues/730
