### ISSUE TITLE
Naming convention for ToolBar (ActionBar)

### ISSUE THREAD

**Issue by tobrunvannuland** [domokit/sky_sdk#9]
Since the introduction of the Material Design Spec the name for the bar on the top of an Application  was replaced with [ToolBar](http://www.google.com/design/spec/components/toolbars.html#) (until then called the ActionBar). I'm suggesting to alter the name to be match the Material specification.

[action_bar.dart](https://github.com/domokit/mojo/blob/efa996dbae1fb7162316841f5a9f3eef58814e78/sky/framework/components/action_bar.dart)

**Comment by abarth** [comment]
Ah, my mistake.  Thanks!

**Comment by Hixie** [comment]
Fixed in https://codereview.chromium.org/1133353008
